UXCorpRangel/js-conf-cl-2024

CONTRIBUTING.md

Update.
El archivo `CONTRIBUTING.md` no muestra información correcta.
Se corrige la información del archivo `CONTRIBUTING.md`.
No.
**Otra información**: Ninguna.

fix: update CONTRIBUTING.md info

---

apps/jsconf/src/components/Slider/Slider.astro
apps/previa/src/components/Slider/Slider.astro

Agrega gradiente en los laterales del slider de las comunidades amigas

feat: :lipstick: add gradients to `Slider` component

---

apps/jsconf/src/components/Footer/Footer.astro
apps/previa/src/components/Footer/Footer.astro

change some style properties to make it similar to the figma design
update
there's no issue about this 
The list items in the footer section are now centered
No

fix: :lipstick: change some style properties

---

apps/jsconf/src/sections/Views.astro
apps/previa/src/components/SpeakerCard.astro
apps/previa/src/sections/Speakers.astro
apps/previa/src/sections/Sponsors.astro
apps/previa/src/sections/Views.astro

Update
Se corrigen errores en la vista mobile
Nop

fix: :lipstick: change responsive styles

---

apps/jsconf/src/components/Footer/Footer.astro
apps/previa/src/components/Footer/Footer.astro

update
There's no issue for this Pull Request
The Footer component change the order
No

fix: :lipstick: change the order of the footer items

---

apps/jsconf/src/components/EventCard.astro
apps/jsconf/src/pages/charlistas/[charlistas].astro

Fix
El responsive lo habíamos dejado regulinchis.
Ahora el responsive va de 9 porque de 10 no puede ir ningún componente.
Nop

fix: :lipstick: improve responsive design

---

apps/jsconf/src/components/Slider/Slider.astro
apps/jsconf/src/components/Slider/data.ts
apps/previa/src/components/Slider/Slider.astro
apps/previa/src/components/Slider/data.ts
apps/previa/src/sections/Speakers.astro

Fix
Se había perdido el logo de la comunidad amiga "Mermelada Tech" en un commit anterior.
Se vuelve a agregar el logo perdido y se elimina un script que no estaba siendo usado.
Nop.

fix: :ambulance: add missing community and remove unused script

---

apps/jsconf/src/components/Navbar/data.ts
apps/jsconf/src/pages/index.astro

feat: :rocket: preparing to deploy

---

apps/previa/src/pages/index.astro

fix: :ambulance: temporally remove streaming componente

---

apps/jsconf/src/components/LiveStreamWidget/config.ts
apps/previa/src/components/LiveStreamWidget/config.ts

fix: :ambulance: update URL

---

apps/jsconf/src/components/LiveStreamWidget/config.ts
apps/previa/src/components/LiveStreamWidget/config.ts

fix
no funsiona el chat debido al hostname.
se corrigio el error del hostname.
no

fix: :ambulance: update hostname configuration for production

---

apps/jsconf/src/components/Button.astro
apps/jsconf/src/sections/Hero.astro

- **Feature**: Actualización de los estilos de los botones en la sección `hero`.
Actualmente, el botón de "Tickets" en la sección `hero` utiliza colores predeterminados que no destacan lo suficiente. Esto afecta la visibilidad del botón y, por ende, la experiencia del usuario.
El nuevo estilo del botón de "Tickets" en la sección `hero` ahora tiene un fondo con un color más visible y las letras son de color blanco, lo que mejora la legibilidad y el atractivo visual. Estos cambios buscan optimizar la conversión al hacer que el botón sea más llamativo.
No, este PR no introduce ningún breaking change. Los usuarios no necesitarán hacer ningún cambio en su aplicación para que este PR funcione correctamente.
Adjunto algunos videos que muestran los cambios realizados en los botones de la sección …

feat(hero): cambie colores del botón de Tickets y letras a blanco

---

apps/jsconf/src/components/Button.astro
apps/jsconf/src/components/SponsorCard.astro
apps/jsconf/src/sections/sponsors/HeroSection.astro

Feature
Se agrega la propiedad `target` y `rel` al componente button y se implementa en la sección de sponsor.
Nop

feat: 🚀 add target blank in button component

---

apps/jsconf/src/data/speakers/charlistas.json

fix
Se arregla un typo en las fechas de las charlas
Nope

fix: ✏️ fix talks date

---

apps/jsconf/src/data/speakers/charlistas.json

fix: ✏️ fix bios

---

apps/jsconf/src/components/FacebookPixel.astro
apps/jsconf/src/layouts/Layout.astro

feature
Se agrega el pixel de facebook para seguimiento de compras
Nope

Facebook pixel

---

apps/jsconf/src/data/agenda/agenda.ts
apps/jsconf/src/data/speakers/charlistas.json

Feature
Se actualiza la agenda con los horarios definitivos
Nop

feat: ✨ update general schedule

---

apps/jsconf/src/layouts/Layout.astro
apps/jsconf/src/sections/Communities.astro
apps/jsconf/src/sections/Sponsors.astro

fix: :bug: fix horizontal scrolling

---

apps/jsconf/src/components/Bento.astro
apps/jsconf/src/data/speakers/charlistas.json
apps/jsconf/src/pages/por-que.astro
apps/jsconf/src/pages/ubicacion.astro

fix: 💄 set new media queries

---

apps/jsconf/src/pages/agenda.astro

fix: 💄 fix section width

---

apps/jsconf/src/data/agenda/agenda.ts
apps/jsconf/src/data/speakers/charlistas.json

feat: 🚀 update schedule
